### ISSUE TITLE
换算的结果在哪里

### ISSUE THREAD

**Issue by yao-yu1999** [HeZhang1994/digital-elevation-model#2]
你好，我用自己的tif图像运行了run_DEM_ASTGDE.py 好像只有reformed之后的tif结果。请问提取经纬度的结果在哪里呢？

**Comment by HeZhang1994** [comment]
> 你好，我用自己的tif图像运行了run_DEM_ASTGDE.py 好像只有reformed之后的tif结果。请问提取经纬度的结果在哪里呢？

你好，你说的“提取经纬度的结果”是指某一经纬度坐标的海拔数值吗？

**Comment by yao-yu1999** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "He ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 晚上10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HeZhang1994/digital-elevation-model] 换算的结果在哪里 (Issue #2)





  
你好，我用自己的tif图像运行了run_DEM_ASTGDE.py 好像只有reformed之后的tif结果。请问提取经纬度的结果在哪里呢？
  
你好，你说的“提取经纬度的结果”是指某一经纬度坐标的海拔数值吗？

**Comment by HeZhang1994** [comment]
> 是的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "He ***@***.***&gt;; 发送时间: 2023年3月27日(星期一) 晚上10:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HeZhang1994/digital-elevation-model] 换算的结果在哪里 (Issue #2) 你好，我用自己的tif图像运行了run_DEM_ASTGDE.py 好像只有reformed之后的tif结果。请问提取经纬度的结果在哪里呢？ 你好，你说的“提取经纬度的结果”是指某一经纬度坐标的海拔数值吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请参考run最后面的这部分代码：# <ASTGDEMv20> Get the elevation from DEM in WGS-84 GCS.
